spring.application.name=demo

# Spring Boot connect with MongoDB
spring.mongodb.uri=mongodb://localhost:27017/ResumeProject1

# spring.security.user.name=ankush
# spring.security.user.password=ankush
